### ISSUE TITLE
High heap consumption on the master branch

### ISSUE THREAD

**Issue by ivan4th** [travelping/upg-vpp#116]
After switching to a newer VPP version (21.01), the master branch started consuming too much heap in some cases (possibly allocated for session structures).

**Comment by korroot** [comment]
Partially address by https://github.com/travelping/upg-vpp/commit/4d92731502af54dbaf2c83a8a43380748e14efe4

**Comment by korroot** [comment]
After merging https://github.com/travelping/upg-vpp/pull/147 and confirming that heap consumption is looking normal, this issue can be closed.
