### ISSUE TITLE
 Rule creation/modification failure

### ISSUE THREAD

**Issue by diallama** [travelping/upg-vpp#118]
I have a Rule creation/modification failure. I use free5gc SMF.
A reflection track would be welcome
[test2.zip](https://github.com/travelping/upg-vpp/files/6386452/test2.zip)

my init file:

create host-interface name vpp-pfcp-peer

set interface state host-vpp-pfcp-peer up

set interface ip address host-vpp-pfcp-peer 172.26.0.50/24

 

create host-interface name vpp-gtp-peer

set interface state host-vpp-gtp-peer up

set interface ip address host-vpp-gtp-peer 172.16.0.1/24

 

create host-interface name vpp-sgi-peer

set interface state host-vpp-sgi-peer up

set interface ip address host-vpp-sgi-peer 192.168.0.2/24

 

upf pfcp endpoint ip 172.26.0.50 vrf 0

 

upf nwi name cp vrf 0

upf nwi name access vrf 100

upf nwi name sgi vrf 200

 

upf gtpu endpoint ip 172.16.0.1 nwi access teid 0x00001234/2

**Comment by RoadRunnr** [comment]
The PID in PDR Id #1 does not contain a valid network instance, the field is there but it is empty. Check you fee5gc config.

Note: TS 29.244 does permit PDRs/PDIs without "Network Instance". The UPG currently has not way to find a suitable network instance (crf) when the IE is not present. The IE with a valid content therefore mandatory for the moment for VPP-UPG.

**Comment by diallama** [comment]
[test.zip](https://github.com/travelping/upg-vpp/files/6441312/test.zip)

sorry it was not the good file. here is the good one. in fact it doesn't know my nwi that I have created via the script described above

**Comment by RoadRunnr** [comment]
Network Instance IE encoding is wrong. The value is encoded as DNN name, but UPG expects a APN name there.

TS 29.244 is very confusing on the details of how Network Instance needs to be encoded. It states that APN is not encoded as FQDN string, that implies the same encoding as in the GTP APN IE is used. The specification is silent about how a DNN is encoded into that IE. That has lead some implementations to encode DNN's as plain binary (FQDN with dots in there, no length indicators).

UPG only understands APN encoding at the moment.

**Comment by diallama** [comment]
ok it's clear. Thanks
