### ISSUE TITLE
upg-vpp doesn't encap gtpu header for downlink traffic 

### ISSUE THREAD

**Issue by redbag-2** [travelping/upg-vpp#136]
Hi, 
I set up upg-vpp as UPF with free5GC SMF, and used UERANSIM to test UE traffic by sending ping requests. 
The uplink tunnel worked well, but the downlink did not. 
Below is my setting and if there was anything wrong?

My startup.conf file
```
unix {
  interactive
  cli-listen /run/vpp/cli-vpp-upf.sock
  exec /home/upf/init.conf
}

cpu {
  main-core 1
  corelist-workers 2-3
}

dpdk {
  socket-mem 2048,2048,2048

  dev 0000:0b:00.0 {
    num-rx-queues 2
    num-rx-desc 1024
    num-tx-queues 2
    num-tx-desc 1024
  }
  
  dev 0000:13:00.0 {
    num-rx-queues 2
    num-rx-desc 1024
    num-tx-queues 2
    num-tx-desc 1024
  }
  
  dev 0000:1b:00.0 {
    num-rx-queues 2
    num-rx-desc 1024
    num-tx-queues 2
    num-tx-desc 1024    
  }
}
```

My init.conf file
```
set int state GigabitEthernet13/0/0 up
set int state GigabitEthernetb/0/0 up
set int state GigabitEthernet1b/0/0 up

set int ip table GigabitEthernet13/0/0 0
set int ip table GigabitEthernetb/0/0 0
set int ip table GigabitEthernet1b/0/0 0

set int ip address GigabitEthernet13/0/0 192.168.1.10/24
set int ip address GigabitEthernetb/0/0 192.168.0.30/24
set int ip address GigabitEthernet1b/0/0 192.168.2.1/24

ip route add 0.0.0.0/0 table 0 via 192.168.2.1 GigabitEthernet1b/0/0

upf pfcp endpoint ip 192.168.1.10 vrf 0

upf nwi name access vrf 0
upf nwi name core vrf 0

upf gtpu endpoint ip 192.168.0.30 nwi access teid 0x00000001/2

upf node-id ip4 192.168.1.10
```

After tracing with vpp debug tools, I found that upg-vpp did not have encap node after interface-output node and thus DL packets were dropped. (vpp gtup plugin has this node) 

```
------------------- Start of thread 2 vpp_wk_1 -------------------
Packet 1

00:07:21:817644: dpdk-input
  GigabitEthernetb/0/0 rx queue 1
  buffer 0x6a2e6: current data 0, length 142, buffer-pool 0, ref-count 1, totlen-nifb 0, trace handle 0x2000001
                  ext-hdr-valid 
                  l4-cksum-computed l4-cksum-correct 
  PKT MBUF: port 0, nb_segs 1, pkt_len 142
    buf_len 2176, data_len 142, ol_flags 0x182, data_off 128, phys_addr 0x9108ba00
    packet_type 0x291 l2_len 0 l3_len 0 outer_l2_len 0 outer_l3_len 0
    rss 0x9e668c47 fdir.hi 0x0 fdir.lo 0x9e668c47
    Packet Offload Flags
      PKT_RX_RSS_HASH (0x0002) RX packet with RSS hash result
      PKT_RX_IP_CKSUM_GOOD (0x0080) IP cksum of RX pkt. is valid
      PKT_RX_L4_CKSUM_GOOD (0x0100) L4 cksum of RX pkt. is valid
    Packet Types
      RTE_PTYPE_L2_ETHER (0x0001) Ethernet packet
      RTE_PTYPE_L3_IPV4_EXT_UNKNOWN (0x0090) IPv4 packet with or without extension headers
      RTE_PTYPE_L4_UDP (0x0200) UDP packet
  IP4: 00:0c:29:5e:21:45 -> 00:0c:29:5d:4b:f1
  UDP: 192.168.0.21 -> 192.168.0.30
    tos 0x00, ttl 64, length 128, checksum 0x941d dscp CS0 ecn NON_ECN
    fragment id 0x24cc, flags DONT_FRAGMENT
  UDP: 2152 -> 2152
    length 108, checksum 0x2cd1
00:07:21:817657: ethernet-input
  frame: flags 0x1, hw-if-index 1, sw-if-index 1
  IP4: 00:0c:29:5e:21:45 -> 00:0c:29:5d:4b:f1
00:07:21:817664: ip4-input
  UDP: 192.168.0.21 -> 192.168.0.30
    tos 0x00, ttl 64, length 128, checksum 0x941d dscp CS0 ecn NON_ECN
    fragment id 0x24cc, flags DONT_FRAGMENT
  UDP: 2152 -> 2152
    length 108, checksum 0x2cd1
00:07:21:817666: ip4-lookup
  fib 0 dpo-idx 8 flow hash: 0x00000000
  UDP: 192.168.0.21 -> 192.168.0.30
    tos 0x00, ttl 64, length 128, checksum 0x941d dscp CS0 ecn NON_ECN
    fragment id 0x24cc, flags DONT_FRAGMENT
  UDP: 2152 -> 2152
    length 108, checksum 0x2cd1
00:07:21:817669: ip4-local
    UDP: 192.168.0.21 -> 192.168.0.30
      tos 0x00, ttl 64, length 128, checksum 0x941d dscp CS0 ecn NON_ECN
      fragment id 0x24cc, flags DONT_FRAGMENT
    UDP: 2152 -> 2152
      length 108, checksum 0x2cd1
00:07:21:817670: ip4-udp-lookup
  UDP: src-port 2152 dst-port 2152
00:07:21:817672: upf-gtpu4-input
  GTPU decap from gtpu_session0 teid 0x00000001 next 1 error 0
00:07:21:817676: upf-ip4-flow-process
  upf_session0 cp-seid 0x0000000000000001
  FlowInfo - sw_if_index 1, next_index = 2
  proto 0x1, 60.60.0.1:0 <-> 192.168.2.10:0, seid 0x0000000000000001
  00000000: 01000000000000000000000000000000000000003c3c00010000000000000000
  00000020: 00000000c0a8020a0000000001000000
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 64, length 84, checksum 0x9829 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573
00:07:21:817680: upf-ip4-input
  upf_session0 cp-seid 0x0000000000000001 pdr 1 far 1
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 64, length 84, checksum 0x9829 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573
00:07:21:817682: upf-ip4-forward
  upf_session0 cp-seid 0x0000000000000001 pdr 1 far 1
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 64, length 84, checksum 0x9829 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573
00:07:21:817684: ip4-input
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 64, length 84, checksum 0x9829 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573
00:07:21:817684: ip4-lookup
  fib 0 dpo-idx 9 flow hash: 0x00000000
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 64, length 84, checksum 0x9829 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573
00:07:21:817685: ip4-rewrite
  tx_sw_if_index 3 dpo-idx 9 : ipv4 via 192.168.2.10 GigabitEthernet1b/0/0: mtu:9000 next:5 000c29232347000c295d4b050800 flow hash: 0x00000000
  00000000: 000c29232347000c295d4b05080045000054a39040003f0199293c3c0001c0a8
  00000020: 020a08003d3340bd0002eb80c1600000000006590800000000001011
00:07:21:817688: GigabitEthernet1b/0/0-output
  GigabitEthernet1b/0/0 
  IP4: 00:0c:29:5d:4b:05 -> 00:0c:29:23:23:47
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 63, length 84, checksum 0x9929 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573
00:07:21:817690: GigabitEthernet1b/0/0-tx
  GigabitEthernet1b/0/0 tx queue 2
  buffer 0x6a2e6: current data 44, length 98, buffer-pool 0, ref-count 1, totlen-nifb 0, trace handle 0x2000001
                  ext-hdr-valid 
                  l4-cksum-computed l4-cksum-correct l2-hdr-offset 0 l3-hdr-offset 58 
  PKT MBUF: port 0, nb_segs 1, pkt_len 98
    buf_len 2176, data_len 98, ol_flags 0x182, data_off 172, phys_addr 0x9108ba00
    packet_type 0x291 l2_len 0 l3_len 0 outer_l2_len 0 outer_l3_len 0
    rss 0x9e668c47 fdir.hi 0x0 fdir.lo 0x9e668c47
    Packet Offload Flags
      PKT_RX_RSS_HASH (0x0002) RX packet with RSS hash result
      PKT_RX_IP_CKSUM_GOOD (0x0080) IP cksum of RX pkt. is valid
      PKT_RX_L4_CKSUM_GOOD (0x0100) L4 cksum of RX pkt. is valid
    Packet Types
      RTE_PTYPE_L2_ETHER (0x0001) Ethernet packet
      RTE_PTYPE_L3_IPV4_EXT_UNKNOWN (0x0090) IPv4 packet with or without extension headers
      RTE_PTYPE_L4_UDP (0x0200) UDP packet
  IP4: 00:0c:29:5d:4b:05 -> 00:0c:29:23:23:47
  ICMP: 60.60.0.1 -> 192.168.2.10
    tos 0x00, ttl 63, length 84, checksum 0x9929 dscp CS0 ecn NON_ECN
    fragment id 0xa390, flags DONT_FRAGMENT
  ICMP echo_request checksum 0x3d33 id 16573

Packet 2

00:07:21:818087: dpdk-input
  GigabitEthernet1b/0/0 rx queue 1
  buffer 0x3dd18: current data 0, length 98, buffer-pool 0, ref-count 1, totlen-nifb 0, trace handle 0x2000002
                  ext-hdr-valid 
                  l4-cksum-computed l4-cksum-correct 
  PKT MBUF: port 2, nb_segs 1, pkt_len 98
    buf_len 2176, data_len 98, ol_flags 0x82, data_off 128, phys_addr 0xa4974680
    packet_type 0x91 l2_len 0 l3_len 0 outer_l2_len 0 outer_l3_len 0
    rss 0xb8ab52c9 fdir.hi 0x0 fdir.lo 0xb8ab52c9
    Packet Offload Flags
      PKT_RX_RSS_HASH (0x0002) RX packet with RSS hash result
      PKT_RX_IP_CKSUM_GOOD (0x0080) IP cksum of RX pkt. is valid
    Packet Types
      RTE_PTYPE_L2_ETHER (0x0001) Ethernet packet
      RTE_PTYPE_L3_IPV4_EXT_UNKNOWN (0x0090) IPv4 packet with or without extension headers
  IP4: 00:0c:29:23:23:47 -> 00:0c:29:5d:4b:05
  ICMP: 192.168.2.10 -> 60.60.0.1
    tos 0x00, ttl 64, length 84, checksum 0x1f9c dscp CS0 ecn NON_ECN
    fragment id 0x5c1e
  ICMP echo_reply checksum 0x4533 id 16573
00:07:21:818097: ethernet-input
  frame: flags 0x1, hw-if-index 3, sw-if-index 3
  IP4: 00:0c:29:23:23:47 -> 00:0c:29:5d:4b:05
00:07:21:818099: ip4-input
  ICMP: 192.168.2.10 -> 60.60.0.1
    tos 0x00, ttl 64, length 84, checksum 0x1f9c dscp CS0 ecn NON_ECN
    fragment id 0x5c1e
  ICMP echo_reply checksum 0x4533 id 16573
00:07:21:818099: ip4-lookup
  fib 0 dpo-idx 6 flow hash: 0x00000000
  ICMP: 192.168.2.10 -> 60.60.0.1
    tos 0x00, ttl 64, length 84, checksum 0x1f9c dscp CS0 ecn NON_ECN
    fragment id 0x5c1e
  ICMP echo_reply checksum 0x4533 id 16573
00:07:21:818106: ip4-arp
    ICMP: 192.168.2.10 -> 60.60.0.1
      tos 0x00, ttl 64, length 84, checksum 0x1f9c dscp CS0 ecn NON_ECN
      fragment id 0x5c1e
    ICMP echo_reply checksum 0x4533 id 16573
00:07:21:818111: ip4-drop
    ICMP: 192.168.2.10 -> 60.60.0.1
      tos 0x00, ttl 64, length 84, checksum 0x1f9c dscp CS0 ecn NON_ECN
      fragment id 0x5c1e
    ICMP echo_reply checksum 0x4533 id 16573
00:07:21:818131: error-drop
  rx:GigabitEthernet1b/0/0
00:07:21:818133: drop
  ip4-arp: ARP requests sent

```
PFCP create PDR message
```
0: handle_session_modification_request:2502: CP F-SEID: 0x0000000000000001 (1) @ 192.168.1.3
UP F-SEID: 0x0000000000000001 (1) @ 192.168.1.10
  SIdx: 0
  Pointer: 0x7fffb8ad10c0
  PDR: 0x7fffb5b46c70
  FAR: 0x7fffbc9f0b60
  PFCP Association: 0
                  (prev:4294967295,next:4294967295)
PDR: 1 @ 0x7fffb5b46c70
  Precedence: 255
  PDI:
    Fields: 0000000d
    Source Interface: Access
    Network Instance: access
    Local F-TEID: 1 (0x00000001)
            IPv4: 192.168.0.30
    UE IP address (source):
      IPv4 address: 60.60.0.1
    SDF Filter [1]:
      permit out ip from any to assigned 
  Outer Header Removal: GTP-U/UDP/IPv4
  FAR Id: 1
  URR Ids: [] @ 0x0
  QER Ids: [1] @ 0x7fffbcc389b0
PDR: 2 @ 0x7fffb5b46cf0
  Precedence: 255
  PDI:
    Fields: 0000000c
    Source Interface: Core
    Network Instance: access
    UE IP address (source):
      IPv4 address: 60.60.0.1
    SDF Filter [1]:
      permit out ip from any to assigned 
  Outer Header Removal: no
  FAR Id: 2
  URR Ids: [] @ 0x0
  QER Ids: [1] @ 0x7fffbcc38a50
FAR: 1 @ 0x7fffbc9f0b60
  Apply Action: 00000002 == [FORWARD]
  Forward:
    Network Instance: access
    Destination Interface: 2
FAR: 2 @ 0x7fffbc9f0bd0
  Apply Action: 00000002 == [FORWARD]
  Forward:
    Network Instance: access
    Destination Interface: 0
    Outer Header Creation: [GTP-U/UDP/IPv4],TEID:00000001,IP:192.168.0.21
    Rewrite Header: UDP: 192.168.0.30 -> 192.168.0.21
                      tos 0x00, ttl 254, length 0, checksum 0x3b69 dscp CS0 ecn NON_ECN
                      fragment id 0x0000
                    UDP: 2152 -> 2152
                      length 0, checksum 0x0000
0: encode_ie:7693: PFCP: Cause: 1.
0: enqueue_response:464: Msg Seq No: 3, idx 2
```

ping pacp file
[ping.zip](https://github.com/travelping/upg-vpp/files/6628131/ping.zip)

**Comment by RoadRunnr** [comment]
Looks like a bug in your SMF, PDR 2 is wrong:
* Source Interface need to be `SGi-LAN/N6-LAN`
* UE IP Address needs to have `S/D` flag set to make it a destination IP

**Comment by redbag-2** [comment]
Thanks, it's work. :)

**Comment by fagadaga** [comment]
@redbag-2 can you share please how you changed these two settings on the smf ? thank you in advance

**Comment by infinitydon** [comment]
@redbag-2 - Can you kindly share how you resolved the networkInstance encoding format on Free5gc SMF?

**Comment by redbag-2** [comment]
Sorry reply so late..
I modify free5gc/NFs/smf/context/datapath.go file, to add Sd flag in UEIPAddress IE.

				ULPDR.PDI = PDI{
					SourceInterface: pfcpType.SourceInterface{InterfaceValue: pfcpType.SourceInterfaceAccess},
					NetworkInstance: []byte(smContext.Dnn),
					LocalFTeid: &pfcpType.FTEID{
						V4:          true,
						Ipv4Address: upIP,
						Teid:        curULTunnel.TEID,
					},
					UEIPAddress: &pfcpType.UEIPAddress{
						Sd:          false,
						V4:          true,
						Ipv4Address: smContext.PDUAddress.To4(),
					},

------------------------------------------------------------------------------------------------------

					DLPDR.PDI = PDI{
						SourceInterface: pfcpType.SourceInterface{InterfaceValue: pfcpType.SourceInterfaceCore},
						LocalFTeid: &pfcpType.FTEID{
							V4:          true,
							Ipv4Address: upIP,
							Teid:        curDLTunnel.TEID,
						},

						UEIPAddress: &pfcpType.UEIPAddress{
						 	Sd:          true,
						 	V4:          true,
						 	Ipv4Address: smContext.PDUAddress.To4(),
						 },
					}
				}

------------------------------------------------------------------------------------------------------

		if curDataPathNode.DownLinkTunnel != nil {
			if curDataPathNode.DownLinkTunnel.SrcEndPoint == nil {
				DNDLPDR := curDataPathNode.DownLinkTunnel.PDR
				DNDLPDR.PDI = PDI{
					SourceInterface: pfcpType.SourceInterface{InterfaceValue: pfcpType.SourceInterfaceCore},
					NetworkInstance: util_3gpp.Dnn(smContext.Dnn),
					UEIPAddress: &pfcpType.UEIPAddress{
						Sd:          true,
						V4:          true,
						Ipv4Address: smContext.PDUAddress.To4(),
					},
				}
			}
		}

**Comment by redbag-2** [comment]
> @redbag-2 - Can you kindly share how you resolved the networkInstance encoding format on Free5gc SMF?

Sorry, I didn't encounter any problems about networkInstance encoding format on Free5gc SMF.
Can you explain your problems more clearly?

**Comment by infinitydon** [comment]
@redbag-2 - First of all, thanks for sharing how you got it working.

With regards the NWI encoding please see the issue below:

https://github.com/travelping/upg-vpp/issues/118#issuecomment-834344277

Can you also kindly share the **_upg-vpp_** and **_Freee5gc_** software version (or commit) that you used? Also if possible the Free5gc SMF config, I will like to compare it with what is currently available in the Free5gc repo.

**Comment by redbag-2** [comment]
@infinitydon 
Hi,
UPG-VPP NWI setting must be equal to smfcfg.conf networkInstance.

And I use ip format in node_id, so UPG-VPP need to setup node_id address.
Below is my init.conf and smfcfg.conf, you can refer it.

init.conf
> set int state GigabitEthernet13/0/0 up // data_plane
> set int state GigabitEthernetb/0/0 up // control_plane
> 
> set int ip table GigabitEthernet13/0/0 0 
> set int ip table GigabitEthernetb/0/0 0 
> 
> set int ip address GigabitEthernetb/0/0 192.168.1.50/24
> set int ip address GigabitEthernet13/0/0 192.168.0.50/24
> 
> ip route add 0.0.0.0/0 table 0 via <gw_ip> GigabitEthernet13/0/0
> 
> upf pfcp endpoint ip 192.168.1.50 vrf 0
> upf nwi name internet vrf 0
> upf gtpu endpoint ip 192.168.0.50 nwi internet teid 0x00000001/2
> 
> upf node-id ip4 192.168.1.50

---------------------------------------------------------------------------------------------
smfcfg.conf
>   userplane_information: # list of userplane information
>     up_nodes: # information of userplane node (AN or UPF)
>       gNB1: # the name of the node
>         type: AN # the type of the node (AN or UPF)
>       UPF:  # the name of the node
>         type: UPF # the type of the node (AN or UPF)
>         node_id: 192.168.1.50 # the IP/FQDN of N4 interface on this UPF (PFCP) -> It must equal to upg-vpp node-id
>         sNssaiUpfInfos: # S-NSSAI information list for this UPF
>           - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
>               sst: 1 
>               sd: 010203 
>             dnnUpfInfoList: # DNN information list for this S-NSSAI
>               - dnn: internet
>                 pools:
>                   - cidr: 60.60.0.0/16
>           - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
>               sst: 1 
>               sd: 112233 # Slice Differentiator
>             dnnUpfInfoList: # DNN information list for this S-NSSAI
>               - dnn: internet
>                 pools:
>                   - cidr: 60.61.0.0/16
>         interfaces: # Interface list for this UPF
>           - interfaceType: N3 # the type of the interface (N3 or N9)
>             endpoints: # the IP address of this N3/N9 interface on this UPF
>               - 192.168.0.50                                                                  -> It must equal to upg-vpp gtpu ip address
>             networkInstance: internet # Data Network Name (DNN) -> It must equal to upg-vpp NWI

Best regards

**Comment by infinitydon** [comment]
Thanks @redbag-2 - Now SMF is able to create PDU session successfully on the upg-vpp:

```
vpp# show upf association
Node: 10.0.4.13
  Recovery Time Stamp: 2021/08/25 09:44:54:000
  Sessions: 0
vpp#
vpp# show upf association
Node: 10.0.4.13
  Recovery Time Stamp: 2021/08/25 09:44:54:000
  Sessions: 1
vpp# show upf session
CP F-SEID: 0x0000000000000001 (1) @ 10.0.4.13
UP F-SEID: 0x0000000000000001 (1) @ 10.0.4.10
  PFCP Association: 0
PDR: 1 @ 0x7fe45dd3cd80
  Precedence: 255
  PDI:
    Fields: 0000000d
    Source Interface: Access
    Network Instance: internet
    Local F-TEID: 1 (0x00000001)
            IPv4: 10.0.6.10
    UE IP address (source):
      IPv4 address: 60.60.0.1
    SDF Filter [1]:
      permit out ip from any to assigned
  Outer Header Removal: GTP-U/UDP/IPv4
  FAR Id: 1
  URR Ids: [] @ 0x0
  QER Ids: [1] @ 0x7fe45dd6c7f0
PDR: 2 @ 0x7fe45dd3ce00
  Precedence: 255
  PDI:
    Fields: 0000000c
    Source Interface: Core
    Network Instance: internet
    UE IP address (destination):
      IPv4 address: 60.60.0.1
    SDF Filter [1]:
      permit out ip from any to assigned
  Outer Header Removal: no
  FAR Id: 2
  URR Ids: [] @ 0x0
  QER Ids: [1] @ 0x7fe45dd6c880
FAR: 1
  Apply Action: 00000002 == [FORWARD]
  Forward:
    Network Instance: internet
    Destination Interface: 2
FAR: 2
  Apply Action: 00000002 == [FORWARD]
  Forward:
    Network Instance: internet
    Destination Interface: 0
    Outer Header Creation: [GTP-U/UDP/IPv4],TEID:00000001,IP:10.0.6.158
```

But ping request is not working, I think this could be because the source interface should be **_SGi-LAN/N6-LAN_** in PDR 2

**Comment by infinitydon** [comment]
@redbag-2 - Sorry to bother you again, please I want to ask about the throughput speed you were able to achieve with the DPDK deployment?

I have used Kubernetes to deploy the vpp-upf with the DPDK interfaces (via sriov-dp) and everything looks fine, I am able to create sessions on the vpp-upf but the iperf throughput is very low:

```
ubuntu@ip-10-0-2-51:~/UERANSIM/build$ ./nr-binder 12.1.1.7 iperf3 -c 10.0.7.167 -i 1 -t 10
Connecting to host 10.0.7.167, port 5201
[  5] local 12.1.1.7 port 42151 connected to 10.0.7.167 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  7.74 MBytes  64.9 Mbits/sec  498   55.3 KBytes
[  5]   1.00-2.00   sec  2.50 MBytes  21.0 Mbits/sec  305   18.4 KBytes
[  5]   2.00-3.00   sec  2.50 MBytes  21.0 Mbits/sec  319   11.8 KBytes
[  5]   3.00-4.00   sec  1.25 MBytes  10.5 Mbits/sec  299   25.0 KBytes
[  5]   4.00-5.00   sec  2.50 MBytes  21.0 Mbits/sec  208   21.1 KBytes
[  5]   5.00-6.00   sec  2.50 MBytes  21.0 Mbits/sec  259   18.4 KBytes
[  5]   6.00-7.00   sec  2.50 MBytes  21.0 Mbits/sec  219   9.21 KBytes
[  5]   7.00-8.00   sec  2.50 MBytes  21.0 Mbits/sec  292   22.4 KBytes
[  5]   8.00-9.00   sec  1.25 MBytes  10.5 Mbits/sec  216   39.5 KBytes
[  5]   9.00-10.00  sec  3.75 MBytes  31.5 Mbits/sec  301   3.95 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  29.0 MBytes  24.3 Mbits/sec  2916             sender
[  5]   0.00-10.00  sec  25.1 MBytes  21.1 Mbits/sec                  receiver

iperf Done.
```
I am using ueransim to test.. Any idea what could be causing the low throughput? I tried running the ueransim on a system with 16 CPU cores but that did not help.

**Comment by redbag-2** [comment]
HI @infinitydon 
The performance bottleneck is on UERANSIM,  you can try free5gc's gtp5g and libgtp5gnl tool to simulate UE.
Or using T-rex, It powerful test tool.
Two way will get better throughput via my test.

Good luck

**Comment by tim-ywliu** [comment]
> Sorry reply so late.. I modify free5gc/NFs/smf/context/datapath.go file, to add Sd flag in UEIPAddress IE.
> 
> ```
> 			ULPDR.PDI = PDI{
> 				SourceInterface: pfcpType.SourceInterface{InterfaceValue: pfcpType.SourceInterfaceAccess},
> 				NetworkInstance: []byte(smContext.Dnn),
> 				LocalFTeid: &pfcpType.FTEID{
> 					V4:          true,
> 					Ipv4Address: upIP,
> 					Teid:        curULTunnel.TEID,
> 				},
> 				UEIPAddress: &pfcpType.UEIPAddress{
> 					Sd:          false,
> 					V4:          true,
> 					Ipv4Address: smContext.PDUAddress.To4(),
> 				},
> ```
> 
> ```
> 				DLPDR.PDI = PDI{
> 					SourceInterface: pfcpType.SourceInterface{InterfaceValue: pfcpType.SourceInterfaceCore},
> 					LocalFTeid: &pfcpType.FTEID{
> 						V4:          true,
> 						Ipv4Address: upIP,
> 						Teid:        curDLTunnel.TEID,
> 					},
> 
> 					UEIPAddress: &pfcpType.UEIPAddress{
> 					 	Sd:          true,
> 					 	V4:          true,
> 					 	Ipv4Address: smContext.PDUAddress.To4(),
> 					 },
> 				}
> 			}
> ```
> 
> ```
> 	if curDataPathNode.DownLinkTunnel != nil {
> 		if curDataPathNode.DownLinkTunnel.SrcEndPoint == nil {
> 			DNDLPDR := curDataPathNode.DownLinkTunnel.PDR
> 			DNDLPDR.PDI = PDI{
> 				SourceInterface: pfcpType.SourceInterface{InterfaceValue: pfcpType.SourceInterfaceCore},
> 				NetworkInstance: util_3gpp.Dnn(smContext.Dnn),
> 				UEIPAddress: &pfcpType.UEIPAddress{
> 					Sd:          true,
> 					V4:          true,
> 					Ipv4Address: smContext.PDUAddress.To4(),
> 				},
> 			}
> 		}
> 	}
> ```

fixed in https://github.com/free5gc/smf/pull/57
