### ISSUE TITLE
IE source/destination interface

### ISSUE THREAD

**Issue by orion-belt** [travelping/upg-vpp#137]
@RoadRunnr 
Sorry it is bit theoretical question.
According to TS 29.244 R 16.05, and section 8.2.24 & 8.2.2,
The "Access" and "Core" values denote an uplink and downlink traffic direction respectively.
i.e. `Core` represents way towards PDN if I understood correctly.

Then in upg implementation why we use SGi-LAN as way to PDN ?

**Comment by RoadRunnr** [comment]
I haven't found an explicit definition for `Core` and `Access`, but TS 23.217, Table 5.2.2-1 gives a clear picture of what is meant.

Traffic in `core` direction applies only to GTP traffic going towards a UPF, the traffic arrives at the UPF from `access` (i.e. from the RAN).
Traffic in `access` direction means GTP traffic from an UPF towards the RAN.

So CORE would be used when describing the GTP path towards the PDN, while SGi/N6 would mean the plain IP path towards PDN.
Also the term PDN and SGi/N6 actually mean the thing (actually SGi being the reference point on the PDN where the UPF attaches to it).

There is also TS 29.244, claus 5.2.1A.2A, that describes how to to apply SDF filter:
> when the Source Interface is CP-function or SGi-LAN, the UP function shall use the Flow Description as is.

**Comment by orion-belt** [comment]
@RoadRunnr 
I have written nrf client code for UPF which will basically expose UPF profile to NRF then SMF (who is subscribed to NRF) will then sends association requests to UPF.

So as VPP-UPF additionally uses nwi, it should be added in UPF profile while registering to NRF.
And it can be done by using InterfaceUpfInfoItem (we can add UPInterfaceType and networkInstance) [TS 29.510, section 6.1.6.2.24](https://www.etsi.org/deliver/etsi_ts/129500_129599/129510/16.04.00_60/ts_129510v160400p.pdf)

Now problem is 6.1.6.3.9 Enumeration: UPInterfaceType does not contains interface N4, so I am bit unclear how nwi for N4 can be added in UPF profile.

I hope it is not off the topic and let me know your suggestion.

**Comment by RoadRunnr** [comment]
From the specifications there is clearly no need to add the N4 interface or the N4 NWI to the profile.

The requirement to declare a NWI for the management GTP tunnel across N4 is clearly something that would be solvable on the VPP-UPG side. The PFCP API should know on which NWI it is currently talking and should use that NWI for the N4 GTP rules as well.

You can open a feature request to fix that, but I can't promise that it will be addressed soon.

As long as that is not solved in VPP-UPG, I would suggest adding a `N4` to the enumeration (in case your NRF permits that).
