### ISSUE TITLE
[Help] MBR values

### ISSUE THREAD

**Issue by diallama** [travelping/upg-vpp#150]
I was trying to interconnect the upg-vpp to free5gc which worked fine after some adaptations (and your support). However I wanted to manage the create QER request within the upg but I have an inconsistency with the MBR. When I display it on the CLI (show upf session), it is different from the MBR on the PDU session request. I would like to know how this IE is managed in the upg (encoding etc...). Thank you in advance for any clarification you can give me.

PDU session trace and show upf session command output are attached
[Trace.zip](https://github.com/travelping/upg-vpp/files/6709304/Trace.zip)

**Comment by RoadRunnr** [comment]
QERs / QoS is currently not implemented in UPG. There are some stubs, most IEs should be decoded, but the logic to enforce any QoS setting is not there.
I don't think it would be too complicated to actually add basic QoS control, but we currently have no immediate plans or timeline to work on it.

That said, I'm going to have a quick lock at your trace to see whether there is anything wrong with MBR en/decoding.
