### ISSUE TITLE
Improvement: Log operational events

### ISSUE THREAD

**Issue by mgumz** [travelping/upg-vpp#157]
Operational events must be logged so they become visible for operations. Such events are not happening in the 1000/s but only once in a while and should not impose any noticeable load onto upg-vpp when logging. Some of such events:

* PFCP Association Established with a SMC (the node name of SMC in addition to the IP)
* PFCP Association Disconnected (from which SMC, IP)
* PFCP Association becomes suspicious (and upg-vpp starts resending Heartbeat-Requests)
* PFCP Association "Lost" 
* NAT-Pool saturation / exhaustion level reached

**Comment by mgumz** [comment]
related: [144](https://github.com/travelping/upg-vpp/issues/144).

**Comment by korroot** [comment]
Closed by: #294
