### ISSUE TITLE
UE IP allocation

### ISSUE THREAD

**Issue by orion-belt** [travelping/upg-vpp#171]
As per 3GPP TS 29.244 V16.0.0, Table 7.5.2.2-2: PDI IE within PFCP Session Establishment Request

Network Instance | O | 
This IE shall be present if the CP function requests the UP function to allocate a UE IP address/prefix and the Traffic Endpoint ID is 				not present. 

So does VPP-UPG supports UE IP allocation ?

**Comment by RoadRunnr** [comment]
No, it does not. We have an internal ticket for that, but it has been sitting in backlog for month.

BTW: the Traffic Endpoint feature you mentioned is also not supported.
