### ISSUE TITLE
UPF exception

### ISSUE THREAD

**Issue by kuanghanqian** [travelping/upg-vpp#178]
![1631928533(1)](https://user-images.githubusercontent.com/69032320/133867684-37c234ed-7012-411d-bdfb-0ff1a9dd0a64.png)
UPF is abnormal. After restart, the UPF can respond to the heartbeat message, so the SMF does not restart the PfCP_ ASSOCIATION_ SETUP_ REQUEST

**Comment by sergeymatov** [comment]
ETSI TS 129 244, clause `6.2.2.2 Heartbeat Request `

`A CP function or UP function shall be prepared to receive a Heartbeat Request at any time (even from unknown peers)
and it shall reply with a Heartbeat Response.`

Clasue  `6.2.2.3 Heartbeat Response`

`The message shall be sent as a response to a received Heartbeat Request. `

Based on Specification, UPF is working as expected. Closing the issue

**Comment by kuanghanqian** [comment]
@sergeymatov Thank you for your answer. I still want to ask why UPF is abnormal. Has this error been solved in the new version?
Thank you very much!

**Comment by sergeymatov** [comment]
@kuanghanqian I cant really say cause original report does not include version of UPG you was running.
We did some changes to function that is visible in the original issue, you can try to check UPG 1.2.3 Release

**Comment by mgumz** [comment]
@kuanghanqian your statement is "After restart, the UPF can respond to the heartbeat message, so the SMF does not restart the PfCP_ ASSOCIATION_ SETUP_ REQUEST" … 

UPG contains the IE "Recovery Timestamp IE" which is changed after the restart of UPG. So, SMF can detect this and act in whatever fashion it desires. UPG won't be silence for an unknown amount of time until every possible SMF might have come to the conclusion that the UPG instance was gone.
