### ISSUE TITLE
run VPP code style checks as part of our CI

### ISSUE THREAD

**Issue by RoadRunnr** [travelping/upg-vpp#2]
VPPs checkstyle should be run for every PR, somehow.

**Comment by ivan4th** [comment]
Second that, will do

**Comment by sergeymatov** [comment]
Pls keep in mind
https://gerrit.fd.io/r/c/vpp/+/22963

**Comment by ivan4th** [comment]
Seems to have some issues atm ...
https://gitlab.com/travelping/upg-vpp/-/jobs/795731032#L32

**Comment by RoadRunnr** [comment]
this seems to work now. @ivan4th ????

**Comment by ivan4th** [comment]
Yes it works as expected now
