### ISSUE TITLE
Forwarding policy 

### ISSUE THREAD

**Issue by orion-belt** [travelping/upg-vpp#228]
https://github.com/travelping/upg-vpp/blob/master/upf/upf_forward.c#L250

Here we already have fib index so ip look up is not required and you can directly send to rewrite node.
```bash
vnet_buffer (b)->sw_if_index[VLIB_TX] =
	rpath->frp_fib_index;
next = UPF_FORWARD_NEXT_IP_LOOKUP;
```

I tried similar approach and it [worked](https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-upf-vpp/-/blob/master/scripts/patches/forwarding_policy_lbo_for_flexcn.patch#L428).

**Comment by sergeymatov** [comment]
Direct jump to ip-rewrite chain won't fit the approach if we have dynamic table of custom routes and there is a need to perform a lookup for some particular traffic. In other words - there is a need to do a lookup in our use case

**Comment by sergeymatov** [comment]
There is a possibility to perform different lookup (like VPP FIB is already doing) based on route path type. Dedicated node and required operations for `ip.adj` or `VLIB_TX` can be done in respect to route path containing in the policy.
Later we will do this

**Comment by orion-belt** [comment]
Thanks a lot @sergeymatov for you information. 
Mapping to `ip_adj` during pre-configuration of policy, will avoids look up for every packet. <br/><br/>

![LBO](https://user-images.githubusercontent.com/44278749/159675822-37f8d4d3-c3a9-48a8-bbe4-3dceeccd9970.png)
