### ISSUE TITLE
facing issue in building e2e

### ISSUE THREAD

**Issue by stepin104796** [travelping/upg-vpp#268]
Hi,

we are using the dockerized environment to run the e2e test.

but on running "make e2e-debug" we are seeing ginkgo errors.

Can someone help me with how to build on the docker container?

**Comment by sergeymatov** [comment]
Hello
What is the UPG version you are running?

**Comment by stepin104796** [comment]
we are using the stable 1.2 version of traveling upg-vpp from Github

**Comment by sergeymatov** [comment]
Please try following things
- checkout on stable branch of UPG (stable/1.2)
- set up appropriate env variables `UPG_BUILDENV_PRIVILEGED=1` and `UPG_BUILDENV=docker`
- run `make update-vpp` to fetch dedicated VPP code base
- run `make buildenv` for downloading of the image and starting of the container. It will bring you to `/src/vpp` directory within containers shell
- go to `/src` directory and run `make test-debug` to build and run integration tests (python-based)
- after this, UPG and VPP will be compiled and installed within the container. So you can now perform e2e tests by running `./hack/e2e` within container

**Comment by stepin104796** [comment]
hi @sergeymatov 
We are able to build the container and run make test-debug and e2e.sh but we see errors.

errors facing in **make test-debug**:
```
TEST RESULTS:
     Scheduled tests: 16
      Executed tests: 9
        Passed tests: 8
       Skipped tests: 1
  Not Executed tests: 7
              Errors: 3
FAILURES AND ERRORS IN TESTS:
  Testcase name: IPv4 UPF Test
      ERROR: setUpClass [setUpClass (test_upf.TestUPFIPv4)]
  Testcase name: IPv4 PGW Test
      ERROR: setUpClass [setUpClass (test_upf.TestPGWIPv4)]
  Testcase name: IPv4 PGW Test
      ERROR: setUpClass [setUpClass (test_upf.TestPGWFTUPIP4)]
TESTCASES WHERE NO TESTS WERE SUCCESSFULLY EXECUTED:
  IPv4 UPF Test
  IPv4 PGW Test
```
Errors facing while running **e2e.sh**:

```
* Kernel GTP-U support not available, using userspace GTP-U only
.
.
.
Cores: [1]
[BeforeEach] VPP
  /src/test/e2e/framework/framework.go:81
[AfterEach] VPP
  /src/test/e2e/framework/framework.go:82
DEBU[0005] >>> show version
• Failure in Spec Setup (BeforeEach) [0.002 seconds]
.
.
.

Ran 115 of 115 Specs in 5.158 seconds
FAIL! -- 0 Passed | 115 Failed | 0 Pending | 0 Skipped
--- FAIL: TestUPG (5.20s)
FAIL

Ginkgo ran 1 suite in 27.107019509s
Test Suite Failed

```
**VM specifications**
```
RAM: 16GB
VCPUs: 8 VCPU
Disk: 120GB
```

**Comment by stepin104796** [comment]
Hi,
Can someone help us debugging and solvig these errors?

**Comment by mgumz** [comment]
@stepin104796 we focus mainly on our customers and have a prio on them. if there is time left, we might support on other areas.

**Comment by stepin104796** [comment]
Hi,

We tried running make test-debug and e2e.sh script in the container but seeing the above mentioned errors.
Can some one help in pointing out how to see the log files when we run these tests.

After running e2e.sh we can see 115 testcase failed message .
Could you please share the prerequisites to run e2e.sh?

Attaching the logs captured on running e2e.sh
[e2e.sh log.txt](https://github.com/travelping/upg-vpp/files/8842736/e2e.sh.log.txt)

**Comment by stepin104796** [comment]
Hi,
We are using stable1.2 version of travelping upg-vpp code .
We followed the steps mentioned by @sergeymatov and are able to create the container and run e2e.sh 
But we see only 110 out of 115 testcases are passed.
```
Summarizing 5 Failures:

[Fail] TDF IPv4 session measurement [proxy] [It] can handle a big number of HTTP connections at once [netem]
/src/test/e2e/upg_e2e.go:1278

[Fail] TDF IPv6 session measurement [proxy] [It] can handle a big number of HTTP connections at once [netem]
/src/test/e2e/upg_e2e.go:1278

[Fail] PGW IPv4 session measurement [proxy] [It] can handle a big number of HTTP connections at once [netem]
/src/test/e2e/upg_e2e.go:1278

[Fail] PGW IPv4 [BeforeEach] PDR replacement [proxy off-on+redirects] doesn't permanently disrupt UPG's HTTP redirects
/src/test/e2e/framework/framework.go:160

[Fail] PGW IPv6 session measurement [proxy] [It] can handle a big number of HTTP connections at once [netem]
/src/test/e2e/upg_e2e.go:1278

Ran 115 of 115 Specs in 6379.182 seconds
FAIL! -- 110 Passed | 5 Failed | 0 Pending | 0 Skipped
--- FAIL: TestUPG (6379.23s)
FAIL

Ginkgo ran 1 suite in 1h46m53.444932662s
Test Suite Failed
```
But on running the **"make test-debug"** still seeing the below errors:
```
TEST RESULTS:
     Scheduled tests: 16
      Executed tests: 9
        Passed tests: 8
       Skipped tests: 1
  Not Executed tests: 7
              Errors: 3
FAILURES AND ERRORS IN TESTS:
  Testcase name: IPv4 UPF Test
      ERROR: setUpClass [setUpClass (test_upf.TestUPFIPv4)]
  Testcase name: IPv4 PGW Test
      ERROR: setUpClass [setUpClass (test_upf.TestPGWIPv4)]
  Testcase name: IPv4 PGW Test
      ERROR: setUpClass [setUpClass (test_upf.TestPGWFTUPIP4)]
TESTCASES WHERE NO TESTS WERE SUCCESSFULLY EXECUTED:
  IPv4 UPF Test
  IPv4 PGW Test
==============================================================================

0 attempt(s) left.
Killing possible remaining process IDs:  998 1000
Not compressing files in temporary directories from failed test runs.
make[1]: *** [Makefile:232: test] Error 1
make[1]: Leaving directory '/src/vpp/test'
make: *** [Makefile:404: test] Error 2
make: Leaving directory '/src/vpp'
```
