### ISSUE TITLE
Call to upf_init()?

### ISSUE THREAD

**Issue by mohammedyaqub** [travelping/upg-vpp#271]
Hi,

I am trying to write my own `main() `which in turn call to `upf_init()` and below is the declaration of upf_init() function.
 ```
static clib_error_t *upf_init (vlib_main_t * vm);
```
- what are the pre steps to initialize the vlib_main_t data structure before hand passing to upf_init() ?
- what are the appropriate functions to be called before calling to upf_init() ?
- Or is there any other way to call upf_init() ?

Please help.

Regards,
Yaqub.

**Comment by sergeymatov** [comment]
Hello
`upf_init` is a plugin init function loaded in a sequence of VPP core/plugins modules. Please check out VPP structuring and node dependencies.
