### ISSUE TITLE
throughput testing

### ISSUE THREAD

**Issue by rajishap** [travelping/upg-vpp#272]
Hi  @ivan4th and All,

Is there any testcase available for throughput testing with VPP UPF in this travelping?
Could you please share the details on how to verify the throughput using this vpp-upf code?

Regards,
Rajisha

**Comment by sergeymatov** [comment]
Hello @rajishap 
Yes, there is a patch https://github.com/travelping/upg-vpp/pull/175/files and `e2e/iperf` branch that you might be interested to use to check throughput via `iperf3` test. But we can't assist you in setting up test case that will fit your request.
Unfortunately we can't share any test details or results we are doing in light of confidentiality.
