### ISSUE TITLE
About TCP sumcheck in GTP

### ISSUE THREAD

**Issue by PoorProg** [travelping/upg-vpp#298]
Hello @ivan4th,
This NOT issue but question.
If  the checksum in TCP header is invalid value, does upf drop it?
(TCP header is included into GTP)

Best Regards

**Comment by RoadRunnr** [comment]
I have not checked it, but my gut response would be: "No, why should it?"

A UPF is a middle box that forwards IP packets. Checking the checksum of the IP fragments makes sense, but looking at the higher layer checksums is IMHO not a task for a middle box.

**Comment by PoorProg** [comment]
Hello, Andreas-san,

Thank for your response!
I have checked that a upg-vpp(UPF) does not check TCP checksum by using debug tool .
Best Regards

**Comment by PoorProg** [comment]
This is OK. And I totally agree with Andreas-san's opinion.
Thank you very much!
