### ISSUE TITLE
VPP Not Starting On Recent Releases

### ISSUE THREAD

**Issue by infinitydon** [travelping/upg-vpp#306]
Hi,

After building container image (**_BUILD_TYPE=release make image_**) from using release 1.6.0 and above (including the latest pull from master), upg-vpp is not able to start:

```
root@vpp-upf-dpdk-84d4d8b8ff-xgglm:/# vpp -c /etc/vpp/startup.conf
vpp: Relink `/lib/x86_64-linux-gnu/libhs_runtime.so.5' with `/lib/x86_64-linux-gnu/libhs.so.5' for IFUNC symbol `dbIsValid'
perfmon              [warn  ]: skipping source 'intel-uncore' - intel_uncore_init: no uncore units found
0: tls_init_ca_chain:609: Could not initialize TLS CA certificates
0: tls_mbedtls_init:644: failed to initialize TLS CA chain
0: tls_init_ca_chain:976: Could not initialize TLS CA certificates
0: tls_openssl_init:1050: failed to initialize TLS CA chain
Aborted
```

startup-config:

```
unix {
  nodaemon
  log /tmp/vpp.log
  full-coredump
  gid vpp
  interactive
  cli-listen /run/vpp/cli.sock
  exec /etc/vpp/init.conf
}

cpu {
  main-core 0
  corelist-workers 18
}
dpdk {
 dev 0000:00:06.0 {name n3}
 dev 0000:00:07.0 {name n4}
 dev 0000:00:08.0 {name n6}
}

api-trace {
  on
}

api-segment {
  gid vpp
}

plugins {
    path /usr/lib/x86_64-linux-gnu/vpp_plugins/
    plugin dpdk_plugin.so { enable }
    plugin gtpu_plugin.so { disable }
    plugin upf_plugin.so { enable }
}
```

```
ip table add 1
ip table add 2

set interface ip table n3 1
set interface mtu 9001 n3
set interface ip address n3 10.0.3.10/24
set interface state n3 up

set interface ip table n4 0
set interface mtu 9001 n4
set interface ip address n4 10.0.4.9/24
set interface state n4 up

set interface ip table n6 2
set interface mtu 9001 n6
set interface ip address n6 10.0.5.9/24
set interface state n6 up

ip route add 0.0.0.0/0 table 2 via 10.0.5.1 n6
ip route add 0.0.0.0/0 table 1 via 10.0.3.1 n3
ip route add 48.0.0.0/8 table 2 via 10.0.5.244 n6

upf pfcp endpoint ip 10.0.4.9 vrf 0

upf nwi name access vrf 1
upf nwi name internet vrf 2

upf gtpu endpoint ip 10.0.3.10 nwi access teid 0x000004d2/2
```

When I disabled the upf plugin, vpp was able to start without any issue, wanted to confirm if there are some changes in the config or any other dependencies with regards to the recent releases?

**Comment by mitmitmitm** [comment]
> ***@***.***:/# vpp -c /etc/vpp/startup.conf
> vpp: Relink `/lib/x86_64-linux-gnu/libhs_runtime.so.5' with `/lib/x86_64-linux-gnu/libhs.so.5' for IFUNC symbol `dbIsValid'
> perfmon              [warn  ]: skipping source 'intel-uncore' - intel_uncore_init: no uncore units found
> 0: tls_init_ca_chain:609: Could not initialize TLS CA certificates
> 0: tls_mbedtls_init:644: failed to initialize TLS CA chain
> 0: tls_init_ca_chain:976: Could not initialize TLS CA certificates
> 0: tls_openssl_init:1050: failed to initialize TLS CA chain
> Aborted

To your startup-config, try adding this line:

    heapsize 2G

**Comment by infinitydon** [comment]
Thanks @mitmitmitm, works now

**Comment by huhujump** [comment]
Hi，Could you share the soultion about the docker-compose and dockerfile？I build it by source code ,and move the upf._plugins.so to the vpp's plugins directory，then I would like to integrate it into OAI.
Looking forward to your reply！Thank you！
