### ISSUE TITLE
About using upg-vpp with free5GC v3.3.0

### ISSUE THREAD

**Issue by s5uishida** [travelping/upg-vpp#343]
Hi,

Has anyone tried using upg-vpp with free5GC v3.3.0?

I am trying to use [oai-cn5g-upf-vpp](https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-upf-vpp) v1.5.1 which is based on upg-vpp, with free5GC v3.3.0, but I am not able to create correct Data-Plane. `PFCP Session Establishment` seems to be successful, but `ping` from UE is strange.

I wrote details about this issue in the free5GC repository as follows.

https://github.com/free5gc/free5gc/issues/457

On the other hand, free5GC v3.2.1 (2023.02.12 version) and oai-cn5g-upf-vpp v1.5.1 can create normal Data-Plane and ping is successful.

If you have any information about this, I would be very glad if you could share it.

Best regards,

--Shigeru

**Comment by mgumz** [comment]
@s5uishida wouldn't it make more sense to open an issue to [oai-cn5g-upf-vpp](https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-upf-vpp) then?

**Comment by RoadRunnr** [comment]
seems to be fixed on free5gc
