### ISSUE TITLE
UPG changes Ethernet Header type field

### ISSUE THREAD

**Issue by AbdallahRustom** [travelping/upg-vpp#366]
I am trying to integrate UPG-VPP with open5gs in docker environment, I successfully performed the attach for the UE, 
but UE can't ping the internet, I noticed that I receive the traffic on the n3 docker interface but no traffic is passed through the n6 interface docker interface , on the other hand I made a packet capture on the PDN container, i receive the ping but the ethernet type filed is set to unknow instead of 0x800 for the ipv4.

also the capture from UPG does not go beyond upf-ip4-input

logs :

[Desktop.zip](https://github.com/travelping/upg-vpp/files/13511844/Desktop.zip)

**Comment by huhujump** [comment]
Hi，do you fix it？Could you share the soultion？ 
Looking forward to your reply！Thank you！
