### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by PranavKumar-15032001** [travelping/upg-vpp#384]
Hi All had a very basic question, regarding upf implementations and generalized 5g-core networks. Actually was wondering based on the performance, what is the decision behind the above project being not being written in the erlang ( although there are gtp tunnels erlang implementations ) ? Also for the 5g core nr functions what are the best languages for each network functions (AMF, SMF, PCF, AUSF, UPF, etc...) ?

**Comment by mgumz** [comment]
@PranavKumar-15032001 We offer consultancy to advise our customers on almost any topic. Use the form and/or the email address listed on https://www.travelping.com/company/contact/ to get further help.
