### ISSUE TITLE
Issue in PFCP association with upg stable/1.13

### ISSUE THREAD

**Issue by aritra-nandy** [travelping/upg-vpp#403]
I am using upg stable/1.13 without using DPDK plugin means the interfaces are in linux kernel level only and using this when I try for PFCP association it is not happening. But if I hand over the interfaces to DPDK that time PFCP association is happening. 

Non DPDK based scenario also I tried with upg stable/1.2 and that time using linux kernel interface PFCP association is happening correctly. 

Can anyone please help me?

Thanks,
Aritra

**Comment by RoadRunnr** [comment]
current UPG release are based on VPP 22.04. Unfortunately, that VPP version has a broken TCP/UDP checksum implementation. This bug only shows up when using af_packet or virtio network drivers.

You need to either rebase UPG to 24.04 or apply this https://github.com/FDio/vpp/commit/19a168496b91b5266908a68f7caa25c83b751923 before building the VPP base image.

**Comment by aritra-nandy** [comment]
It's working thank you so much for your support.
