### ISSUE TITLE
session_establishment failed due to missing PDI information F-TEID

### ISSUE THREAD

**Issue by orion-belt** [travelping/upg-vpp#41]
When CH field in F-TEID is set then UPF should handle TEID allocation and report teid in response (TS 29.244, 8.2.3, bit3 CH).
But I see error of mandatory IE is missing.
Am I correct and this is to be handled ?
```
Frame 14: 164 bytes on wire (1312 bits), 164 bytes captured (1312 bits) on interface eth0, id 0
Ethernet II, Src: 02:42:c0:a8:3d:c4 (02:42:c0:a8:3d:c4), Dst: 02:42:c0:a8:3d:c5 (02:42:c0:a8:3d:c5)
Internet Protocol Version 4, Src: 192.168.61.196, Dst: 172.21.16.2
User Datagram Protocol, Src Port: 56768, Dst Port: 8805
Packet Forwarding Control Protocol
    Flags: 0x21, SEID (S)
        001. .... = Version: 1
        ...0 .... = Spare: 0
        .... 0... = Spare: 0
        .... .0.. = Spare: 0
        .... ..0. = Message Priority (MP): False
        .... ...1 = SEID (S): True
    Message Type: PFCP Session Establishment Request (50)
    Length: 118
    SEID: 0x0000000000000000
    Sequence Number: 601419
    Spare: 0
    Node ID : IPv4 address: 192.168.61.196
    F-SEID : SEID: 0x0000000000000001, IPv4 192.168.61.196
    Create PDR : [Grouped IE]
        IE Type: Create PDR (1)
        IE Length: 50
        PDR ID : 1
        Precedence : 15
        PDI : [Grouped IE]
            IE Type: PDI (2)
            IE Length: 19
            Source Interface : Access
                IE Type: Source Interface (20)
                IE Length: 1
                0000 .... = Spare: 0
                .... 0000 = Source Interface: Access (0)
            F-TEID : 
                IE Type: F-TEID (21)
                IE Length: 1
                Flags: 0x04, CH (CHOOSE)
                    0000 .... = Spare: 0
                    .... 0... = CHID (CHOOSE_ID): False
                    .... .1.. = CH (CHOOSE): True
                    .... ..0. = V6 (IPv6): Not Present
                    .... ...0 = V4 (IPv4): Not Present
            UE IP Address : 
        Outer Header Removal : GTP-U/UDP/IPv4
        FAR ID : Dynamic by CP 1
    Create FAR : [Grouped IE]
    [Response In: 15]

```

Response message -
```
Frame 15: 69 bytes on wire (552 bits), 69 bytes captured (552 bits) on interface eth0, id 0
Ethernet II, Src: 02:42:c0:a8:3d:c5 (02:42:c0:a8:3d:c5), Dst: 02:42:c0:a8:3d:c4 (02:42:c0:a8:3d:c4)
Internet Protocol Version 4, Src: 172.21.16.2, Dst: 192.168.61.196
User Datagram Protocol, Src Port: 8805, Dst Port: 56768
Packet Forwarding Control Protocol
    Flags: 0x21, SEID (S)
        001. .... = Version: 1
        ...0 .... = Spare: 0
        .... 0... = Spare: 0
        .... .0.. = Spare: 0
        .... ..0. = Message Priority (MP): False
        .... ...1 = SEID (S): True
    Message Type: PFCP Session Establishment Response (51)
    Length: 23
    SEID: 0x0000000000000000
    Sequence Number: 601419
    Spare: 0
    Cause : Mandatory IE missing
    Offending IE : PDI
        IE Type: Offending IE (40)
        IE Length: 2
        Type of the offending IE: PDI (2)
    [Response To: 14]
    [Response Time: 0.000559919 seconds]
```

**Comment by RoadRunnr** [comment]
Your requests looks like a broken SMF blindly requesting the TEID selection by UPF without honoring the FTUP feature indication.

A UPF indicates whether is supports UPF based TEID assignment through the `FTUP` flag in the `UP Function Features` IE.
A SMF or PGW-C should not attempt to use the CH flags in the TEDI unless the UPF has set the `FTUP` flag.

Rel.16 made the UPF based TEID assignment mandatory.

The latest version of UPG (this implementation) can run in R15 mode **without** FTUP support or in R16 mode with FTUP support. This is controlled through the `upf specification release [15|16]` cli command (15 is the default).

**Comment by orion-belt** [comment]
Hello Andreas,
Thanks a lot for prompt reply.
Yes It is bug at spgwc/smf that it does not honor FTUP unset flag.

Now I made upf specification release 16, & I can see FTUP flag is set now. But I still see Mandatory IE missing message as attached in pcap. 
```
DBGvpp# show upf specification release
PFCP version: 16
```
[spgwc_failure.zip](https://github.com/travelping/upg-vpp/files/5702845/spgwc_failure.zip)

Only thing I see minning is Network Instance in PDI which is optional.

**Comment by RoadRunnr** [comment]
There are two problems with the request:

* for UPG the Network Instance IE is mandatory, this deviates from the specification that has this IE as optional
* in the F-TEID IE, either v4 or v6 or both need to be set, leaving both at 0 is not valid

**Comment by orion-belt** [comment]
I added these two fields in IE as below -
```
PDI : [Grouped IE]
    IE Type: PDI (2)
    IE Length: 29
    Source Interface : Access
    F-TEID : 
        IE Type: F-TEID (21)
        IE Length: 1
        Flags: 0x05, CH (CHOOSE), V4 (IPv4)
            0000 .... = Spare: 0
            .... 0... = CHID (CHOOSE_ID): False
            .... .1.. = CH (CHOOSE): True
            .... ..0. = V6 (IPv6): Not Present
            .... ...1 = V4 (IPv4): Present
    Network Instance : access
        IE Type: Network Instance (22)
        IE Length: 6
        Network Instance: access
    UE IP Address : 
        IE Type: UE IP Address (93)
        IE Length: 5
        Flags: 0x02, V4 (IPv4)
        IPv4 address: 12.1.1.2
```
Now upg crashes with below message -
```
DBGvpp# host-n3
host-n4
host-n6-pri
host-n6-sec
./build-root/install-vpp_debug-native/vpp/bin/vpp: symbol lookup error: /upf/build-root/install-vpp_debug-native/vpp/lib/vpp_plugins//upf_plugin.so: undefined symbol: vlib_decrement_simple_counter
root@adf7a95156e1:/upf# 
```

**Comment by RoadRunnr** [comment]
The crash is a problem with your build, please rebuild vpp from scratch.

Maybe @ivan4th has more idea.

**Comment by orion-belt** [comment]
Sorry for lengthy discussion,

I am using fresh build now. 
But still unable to create session when CH flag is set along with v4.
Please find attached pcap file for session request details -
```
    Create PDR : [Grouped IE]
        IE Type: Create PDR (1)
        IE Length: 60
        PDR ID : 1
            IE Type: PDR ID (56)
            IE Length: 2
            Rule ID: 1
        Precedence : 15
        PDI : [Grouped IE]
            IE Type: PDI (2)
            IE Length: 29
            Source Interface : Access
            F-TEID : 
                IE Type: F-TEID (21)
                IE Length: 1
                Flags: 0x05, CH (CHOOSE), V4 (IPv4)
                    0000 .... = Spare: 0
                    .... 0... = CHID (CHOOSE_ID): False
                    .... .1.. = CH (CHOOSE): True
                    .... ..0. = V6 (IPv6): Not Present
                    .... ...1 = V4 (IPv4): Present
            Network Instance : access
            UE IP Address : 
        Outer Header Removal : GTP-U/UDP/IPv4
        FAR ID : Dynamic by CP 1
    Create FAR : [Grouped IE]
    [Response In: 19]

```
Session response -
```
Packet Forwarding Control Protocol
    Flags: 0x21, SEID (S)
    Message Type: PFCP Session Establishment Response (51)
    Length: 41
    SEID: 0x0000000000000001
    Sequence Number: 3822037
    Spare: 0
    Cause : Rule creation / modification Failure
        IE Type: Cause (19)
        IE Length: 1
        Cause: Rule creation / modification Failure (73)
    F-SEID : SEID: 0x0000000000000001, IPv4 172.21.16.2
        IE Type: F-SEID (57)
        IE Length: 13
        Flags: 0x02, V4 (IPv4)
            0... .... = Spare: 0
            .0.. .... = Spare: 0
            ..0. .... = Spare: 0
            ...0 .... = Spare: 0
            .... 0... = Spare: 0
            .... .0.. = Spare: 0
            .... ..1. = V4 (IPv4): Present
            .... ...0 = V6 (IPv6): Not Present
        SEID: 0x0000000000000001
        IPv4 address: 172.21.16.2
    Failed Rule ID : PDR: 1
        IE Type: Failed Rule ID (114)
        IE Length: 3
        .... .000 = Failed Rule ID Type: PDR (0)
        Rule ID: 1
    [Response To: 18]
    [Response Time: 0.001520172 seconds]

```

[session_failure.zip](https://github.com/travelping/upg-vpp/files/5724616/session_failure.zip)

**Comment by RoadRunnr** [comment]
The request look good, the most probable remaining cause is a configuration problem.

It is very likely that the network instance `access` has not be configure as GTP-U endpoint. A config statement like e.g. `upf gtpu endpoint ip 10.0.0.2 nwi access teid 0x80000000/2`. Of course, the network instance `access` also need to be declared.

Can you share you VPP/UPG config for further inspection?

**Comment by orion-belt** [comment]
Hi
Please check my config file. UPF gtpu endpoint is N3 interface ip here.
```
ip table add 1
ip table add 2
ip table add 3
ip6 table add 1
ip6 table add 2
ip6 table add 3

create host-interface name n3
set interface mac address host-n3 00:0c:29:46:1f:53
set interface mtu 1500 host-n3 
set interface ip table host-n3 1
set interface ip6 table host-n3 1
set interface ip address host-n3 172.20.16.2/24
set interface state host-n3 up

create host-interface name n4    
set interface mac address host-n4 00:0c:29:46:1f:54
set interface mtu 1500 host-n4    
set interface ip table host-n4 0
set interface ip6 table host-n4 0
set interface ip address host-n4 172.21.16.2/24
set interface state host-n4 up

create host-interface name n6-pri
set interface mac address host-n6-pri 00:0c:29:46:1f:55
set interface mtu 1500 host-n6-pri
set interface ip table host-n6-pri 2
set interface ip6 table host-n6-pri 2
set interface ip address host-n6-pri 172.22.16.2/24
set interface state host-n6-pri up

create host-interface name n6-sec
set interface mac address host-n6-sec 00:0c:29:46:1f:51
set interface mtu 1500 host-n6-sec
set interface ip table host-n6-sec 3
set interface ip6 table host-n6-sec 3
set interface ip address host-n6-sec 172.23.16.2/24
set interface state host-n6-sec up

upf pfcp endpoint ip 172.21.16.2 vrf 0

ip route add 192.168.61.196/32 table 0 via 172.21.16.3 host-n4
ip route add 192.168.61.210/32 table 1 via 172.20.16.3 host-n3
ip route add 0.0.0.0/0 table 2 via 172.22.16.3 host-n6-pri
ip route add 0.0.0.0/0 table 3 via 172.23.16.3 host-n6-sec

upf nwi name cp vrf 0
upf nwi name access vrf 1
upf nwi name sgi1 vrf 2
upf nwi name sgi2 vrf 3

upf specification release 16
trace add af-packet-input 100

upf gtpu endpoint ip 172.20.16.2 nwi access teid 0x000004d2/2
```

**Comment by RoadRunnr** [comment]
config looks ok. But VPP has the annoying habit of aborting config parsing once it hits a single error. It could therefore be that your gtpu endpoint statement is not executed. You can check that with "show upf gtpu endpoint".

Another concern is that you are clearly using a modified UPF version. There could be something wrong with the changes in your tree.

You can either try with the vanilla source from the master branch, or you try to instrument your version with enough clib_warnings in the PDR processing to find the cruelpint.

**Comment by RoadRunnr** [comment]
one more thing, you can run the e2e tests with `make e2e-debug` on your version to make nothing obvious is broken.

**Comment by orion-belt** [comment]
Yes I am validating my setup. Please let me know if you think following point I debug if is due to broken setup ?

During `handle_create_pdr`, nwi lookup is done. Problem I see is memory pointer to nwi hashtable is not retrived. Hence session creation fails. In entire code this hastable is only unset while removing nwi so I am bit surprised why information is not retrieved inlookup_nwi() method.
Below I printed hastable pointer when it is nwi hastable is retrieved 

```
 __/ __/ _ \  (_)__    | | / / _ \/ _ \
 _/ _// // / / / _ \   | |/ / ___/ ___/
 /_/ /____(_)_/\___/   |___/_/  /_/    

DBGvpp# 
DBGvpp# 
host-n3
hos
host-n6-pri
host-n6-sec
vnet_upf_create_nwi_if:218: nwi_index_by_name mem pointer 1518152448, name cp
vnet_upf_create_nwi_if:218: nwi_index_by_name mem pointer 1518152752, name access
vnet_upf_create_nwi_if:218: nwi_index_by_name mem pointer 1520334812, name sgi1
vnet_upf_create_nwi_if:218: nwi_index_by_name mem pointer 1518153344, name sgi2

DBGvpp# 
DBGvpp# show upf nwi name access
access, ip4-fib-index 1, ip6-fib-index 1
upf_show_nwi_command_fn:335: nwi_index_by_name mem pointer 1520334796, name access
DBGvpp# 
DBGvpp# show upf nwi name cp    
cp, ip4-fib-index 0, ip6-fib-index 0
upf_show_nwi_command_fn:335: nwi_index_by_name mem pointer 1518152448, name cp
DBGvpp# 
DBGvpp# show upf nwi name sgi1
sgi1, ip4-fib-index 2, ip6-fib-index 2
upf_show_nwi_command_fn:335: nwi_index_by_name mem pointer 1520334812, name sgi1
DBGvpp# 
DBGvpp# 

######
session_establishment_req from control plane 
######


DBGvpp# lookup_nwi:590: nwi_index_by_name mem pointer 0, name access  ####### nwi hashtable not retrieved #####
handle_create_pdr:843: PDR: 1, PDI for unknown network instance
handle_create_pdr:846: NWI: access (6)

DBGvpp# 
DBGvpp# show upf nwi name cp  
cp, ip4-fib-index 0, ip6-fib-index 0
upf_show_nwi_command_fn:335: nwi_index_by_name mem pointer 1518152448, name cp
DBGvpp#                     
DBGvpp# show upf nwi name access
access, ip4-fib-index 1, ip6-fib-index 1
upf_show_nwi_command_fn:335: nwi_index_by_name mem pointer 1520334796, name access
DBGvpp# 
```

**Comment by RoadRunnr** [comment]
Ahh, this seems to be the common trap of the network instance encoding. Even the wireshark devs couldn't make up their mind about the correct reading the specification and settled for (what I think is a) half backed compromise. I should have seen this earlier.

TS 29.244, 8.2.4 Network Instance states:

> It may be encoded as a Domain Name or an Access Point Name (APN) as per clause 9.1 of 3GPP TS 23.003 [2].
> ...
> NOTE: The APN field is not encoded as a dotted string as commonly used in documentation.

There seems to be the common understanding that the "NOTE" means that a APN name is encoded a with the DNS label length encoding that is commonly use in other places (e.g. GTP). However, some seem to read this in a way that is legal to encode a "Domain Name" as a plain string (I don't subscribe to that theory). The wireshark decoder selects between the two encoding by looking at the first byte, if it is greater than 64, it assumes a plain string, otherwise it assumes a DNS label encoding.

UPG internally always uses DNS label encoding for network instances and also expects the Network Instance IE to always contain a DNS label encoded value.

Your example uses a plain string in the Network Instance IE. Thaa plain string can not be matched against the internally used label encoding, leading to the problem you are seeing.

**Comment by orion-belt** [comment]
You were right. It was [plan string only](https://github.com/OPENAIRINTERFACE/openair-spgwc/blob/vpp_upf/src/oai_spgwc/pgwc_procedure.cpp#L186).
I used upf_name_to_lables() temporarily to fix this issue. Session establishment with TEID generation is successfully done now.
I verified session with `show upf session`.

thanks a lot :)

**Comment by RoadRunnr** [comment]
BTW: you can use [erGW](https://github.com/travelping/ergw) as P-GW or SAE-GW as well ;-)
