### ISSUE TITLE
Memory leak when using proxy

### ISSUE THREAD

**Issue by ivan4th** [travelping/upg-vpp#51]
There's a memory leak in UPG when using proxy, possibly mostly for non-stitched TCP connections.
The leak is not visible in `show memory`, but vpp RSS keeps increasing.
It is likely related to SVM FIFOs being not properly freed.

Below is a flame graph constructed from page fault tracing with perf (based on [1]).
<img width="1197" alt="Flame Graph" src="https://user-images.githubusercontent.com/190448/103213588-352eb780-491f-11eb-9c8e-aa8ef32ec9ce.png">

[1] http://www.brendangregg.com/FlameGraphs/memoryflamegraphs.html

**Comment by RoadRunnr** [comment]
I'm not convinced that the memory is indeed leaking. In order to archive decent performance, the socket buffers per connection have to be quite large. Some megabyte per connection are reasonable. The total memory required for all sockets on a medium load can easily top multiple gigabytes.

**Comment by ivan4th** [comment]
The leak is no longer observed as of v1.1.4 (after #67 was merged before an earlier release)
