### ISSUE TITLE
lookup_nwi "epc" fail,but in init.conf has config ,and cli cmomand "show upf nwi "is correct

### ISSUE THREAD

**Issue by jinboc** [travelping/upg-vpp#53]
ip table add 100
ip table add 200
ip6 table add 100
ip6 table add 200
upf nwi name cp table 0
upf nwi name epc table 100
upf nwi name apn table 200

**Comment by sergeymatov** [comment]
Hello
Could you please try to change upf nwi creation lines to
upf nwi name <name> vrf <id>

**Comment by RoadRunnr** [comment]
> Hello
> Could you please try to change upf nwi creation lines to
> upf nwi name _name_ vrf _id_

@sergeymatov `vrf` and `table` are identical in the upf nwi command.
@jinboc your issue is most likely the same encoding issue of the Network Instance IE as in #41. Your SMF is most likely sending a string encoded domain name while the UPG implementation expects a DNS label encoded value.

**Comment by jinboc** [comment]
The Network instance field shall be encoded as an OctetString and shall contain an identifier which uniquely identifies a particular Network instance (e.g. PDN instance) in the UP function. It may be encoded as a Domain Name or an Access Point Name (APN) as per clause 9.1 of 3GPP TS 23.003 [2]. In the latter case, the PDN Instance field may contain the APN Network Identifier only or the full APN with both the APN Network Identifier and the APN Operator Identifier as specified in 3GPP TS 23.003 [2] clauses 9.1.1 and 9.1.2.
NOTE:	The APN field is not encoded as a dotted string as commonly used in documentation.
but in code:
static int
decode_simple_vec_ie (u8 * data, u16 length, void *p)
{
  u8 **v = p;

  vec_reset_length (*v);
  vec_add (*v, data, length);

  return 0;
}
#define decode_network_instance decode_simple_vec_ie
but in code,the ie of network instance decode  as a string.i can't understand it.

**Comment by RoadRunnr** [comment]
> but in code,the ie of network instance decode as a string.i can't understand it.

It's not decoded as string, a verbatim copy onto a vector is made. This preserves the existing internal encoding of the IE.
UPG expects that this internal encoding uses the DNS label scheme. The `upf nwi` CLI command translates the network instance name into that encoding as well.

**Comment by jinboc** [comment]
thanks very much
