### ISSUE TITLE
 Failed to test app detect，What's wrong with me。

### ISSUE THREAD

**Issue by jinboc** [travelping/upg-vpp#66]
first use clito config appid,suck as
create upf application proxy name 111
upf application 111 rule 3000 add l7 regex ^https?://(.*\\.)*(example)\\.com/
upf application 111 rule 3001 add ipfilter permit out ip from any to assigned
then contrust pdr with application 111 ie .
then eatablish session ,
all is ok

Simulate a mobile phone to visit an app。
but show trace ,i find pdrindex is error.No proxy node，i think It must pass the node of proxy

**Comment by jinboc** [comment]
i think function upf_acl_classify_forward line264 incorrect,should be pdr->pdi.fields & F_PDI_APPLICATION_ID
	    far = pfcp_get_far_by_id (active, pdr->far_id);
	    if (flow->key.proto == IP_PROTOCOL_TCP &&
		far && far->forward.flags & FAR_F_REDIRECT_INFORMATION)

**Comment by ivan4th** [comment]
Hi, could you share a .pcap files with PFCP Session Establishment Request and also the connection that is not proxied?

**Comment by jinboc** [comment]
URL mismatch，I mainly want to learn about the process。
[n4.zip](https://github.com/travelping/upg-vpp/files/5813535/n4.zip)
[n3.zip](https://github.com/travelping/upg-vpp/files/5813537/n3.zip)
