### ISSUE TITLE
upf.api does not support layer-4 port or range?

### ISSUE THREAD

**Issue by hesingh** [travelping/upg-vpp#97]
This is the API

https://github.com/travelping/upg-vpp/blob/5129d0d9fd79cd1e0b7e143d96b0b3c5a5997567/upf/upf.api

I think the UPG code supports matching prefix and layer-4 port range.  But, I don't see layer-4 port info in the API.

**Comment by RoadRunnr** [comment]
@hesingh the VPP binary API is not used for the policies. It can only be used for preconfiguring ADF rules. Preconfiguring IP bases SDFs can only done through the VPP CLI.

SDFs with ports can be set through the PFCP protocol in PDRs / PDIs. There the full range of the IPFilterRule as specified by 3GPP TS 29.212 clause 5.4.2 and 3GPP TS 29.214 clause 5.3.8 is supported. That does include port ranges.
